### ISSUE TITLE
with-afterjs example

### ISSUE THREAD

**Issue by joshua1** [jaredpalmer/after.js#113]
Hi @jaredpalmer i was created an app using the after.js example and tried swapping out the express server for a fastify one. it seems there is a tight coupling of razzle start with the express api as i got the below error 
```
events.js:239
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:265:10)
    at Object.createServer (http.js:34:10)
    at Object../src/index.js (/Users/admin/Documents/Development_Stuff/A/myApps/uBus/Sample2/build/server.js:1160:59)
    at __webpack_require__ (/Users/admin/Documents/Development_Stuff/A/myApps/uBus/Sample2/build/server.js:630:30)
    at fn (/Users/admin/Documents/Development_Stuff/A/myApps/uBus/Sample2/build/server.js:48:20)
    at Object.0 (/Users/admin/Documents/Development_Stuff/A/myApps/uBus/Sample2/build/server.js:1336:18)
    at __webpack_require__ (/Users/admin/Documents/Development_Stuff/A/myApps/uBus/Sample2/build/server.js:630:30)
    at __dirname../build/assets.json.module.exports.client.js (/Users/admin/Documents/Development_Stuff/A/myApps/uBus/Sample2/build/server.js:676:37)
```

my replacement is like

```
const assets = require(process.env.RAZZLE_ASSETS_MANIFEST)

fastify.register(require('fastify-static'), {
	root: process.env.RAZZLE_PUBLIC_DIR
})
fastify.register(require('fastify-helmet'), {
	hidePoweredBy: { setTo: 'SyamoreLabs' }
})
fastify.get('/*', async (req, res) => {
	try {
		const html = await render({
			req,
			res,
			routes,
			assets,
			// Anything else you add here will be made available
			// within getInitialProps(ctx)
			// e.g a redux store...
			customThing: 'thing'
		})
		res.send(html)
	} catch (error) {
		res.json(error)
	}
})

const server = fastify

export default server
```

maybe i am doing something wrong here

**Comment by joshua1** [comment]
i think i got it working . i didnt need to make some of the changes here 
```
import fastify from 'fastify'
import { render } from '@jaredpalmer/after'
import routes from './routes'

const assets = require(process.env.RAZZLE_ASSETS_MANIFEST)

const server = fastify()
server
	//.disable('x-powered-by')
	.register(require('fastify-helmet'), {
		hidePoweredBy: { setTo: 'SyamoreLabs' }
	})
	.use(fastify.static(process.env.RAZZLE_PUBLIC_DIR))
	.get('/*', async (req, res) => {
		try {
			const html = await render({
				req,
				res,
				routes,
				assets,
				// Anything else you add here will be made available
				// within getInitialProps(ctx)
				// e.g a redux store...
				customThing: 'thing'
			})
			res.send(html)
		} catch (error) {
			res.json(error)
		}
	})

export default server
```

**Comment by joshua1** [comment]
still not working

**Comment by joshua1** [comment]
with-afterjs example project actually doesn't work  with the latest release of afterjs. only renders 
```
{} 
```
on start

**Comment by joshua1** [comment]
I don't know what the changes are for 1.2.0 but i switched back to 1.1.0 and was able to get the app running . will stick to 1.1.0 until the issue is resolved

**Comment by John0x** [comment]
This is caused by the new document.tsx. It's trying to read the properties of helmet even though helmet is undefined.

**Comment by John0x** [comment]
Fixed this by using the custom document.tsx and replaccing this:
````
  public static getInitialProps({ assets, data, renderPage }: any) {
    const page = renderPage();
    return { assets, data, ...page };
  }
````
with this:
````
  public static async getInitialProps({ assets, data, renderPage }: any) {
    const page = await renderPage();
    return { assets, data, ...page };
  }
````

**Comment by fdaciuk** [comment]
Thanks @John0x! It works like a charm =)
