### ISSUE TITLE
Doc.getInitialProps when starting razzle

### ISSUE THREAD

**Issue by SaraVieira** [jaredpalmer/after.js#141]
## Bug, Feature, or Question?
Bug

## Current Behavior
I am trying to turn a preact app to after.js and I get this error: 

```
TypeError: Doc.getInitialProps is not a function
    at /Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/render.js:123:46
    at step (/Users/saravieira/Projects/awesome-talks/node_modules/@jare
dpalmer/after/build/render.js:40:23)
    at Object.next (/Users/saravieira/Projects/awesome-talks/node_module
s/@jaredpalmer/after/build/render.js:21:53)
    at fulfilled (/Users/saravieira/Projects/awesome-talks/node_modules/
@jaredpalmer/after/build/render.js:12:58)
    at <anonymous>
TypeError: Doc.getInitialProps is not a function
    at /Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/render.js:123:46
    at step (/Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/render.js:40:23)
    at Object.next (/Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/render.js:21:53)
    at fulfilled (/Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/render.js:12:58)
    at <anonymous>
```

I have deleted all instances of Preact and also followed this https://www.apollographql.com/docs/react/features/server-side-rendering.html in order to try and get Apollo to work but then got stuck here. It's probably something small but I have been stuck for a couple of hours

## Desired Behavior
Run the website

## Suggested Solutions
No idea :(

## Additional Information

---

- After.js Version: 1.3.1
- Razzle Version: 2.0.0-alpha.12
- React Version: 16.4.0
- OS: Mac
- Node Version: v9.4.0
- Package Manager and Version: yarn - 1.6.0
- Demo Repo or Link: https://github.com/SaraVieira/awesome-talks/tree/37

**Comment by jaredpalmer** [comment]
Let me take a look.

**Comment by SaraVieira** [comment]
Hey !

Turns out that was a Apollo problem, sorry, I just pushed a new version to github but I am getting:

```
Using .eslintrc defined in your app root
Using .eslintrc defined in your app root
✔ success client compiled in 4s 769ms
✔ success server compiled in 3s 359ms
{}
✅  Server-side HMR Enabled!
(node:82495) UnhandledPromiseRejectionWarning: ReferenceError: window is
 not defined
    at /Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalme
r/after/build/ensureReady.js:48:78
    at Array.map (<anonymous>)
    at /Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalme
r/after/build/ensureReady.js:47:65
    at step (/Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/ensureReady.js:32:23)
    at Object.next (/Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/ensureReady.js:13:53)
    at /Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/ensureReady.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/ensureReady.js:3:12)
    at ensureReady (/Users/saravieira/Projects/awesome-talks/node_modules/@jaredpalmer/after/build/ensureReady.js:43:12)
    at Object../src/client.js (/Users/saravieira/Projects/awesome-talks/build/server.js:4886:71)
(node:82495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handledwith .catch(). (rejection id: 2)
(node:82495) [DEP0018] DeprecationWarning: Unhandled promise rejectionsare deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
🚀 started on http://localhost:3000
```

Any ideas ?

**Comment by jaredpalmer** [comment]
pathname is probably undefined

**Comment by jaredpalmer** [comment]
Hrmmm. V strange. I’m can take a deeper dive this evening.

**Comment by SaraVieira** [comment]
It also does a weird refreshing on the front-end but I'll try to figure it out!

If you get time feel free to download my branch :)
