### ISSUE TITLE
css problem with after.js

### ISSUE THREAD

**Issue by singlepageprogrammer** [jaredpalmer/after.js#220]
there is a problem with load css in after.js ...
css code&&files have a delay when page loads
after any refresh i first see some html preview without css styles and after seconds it will be load
is there any standard way for solve that ?

**Comment by nimaa77** [comment]
because of Code Splitting, the css and js files get fetched after HTML gets parsed on the client side.
to fix this just use [afterjs-assets](https://github.com/nimacsoft/afterjs-assets)

**Comment by singlepageprogrammer** [comment]
thx it worked for me :)

**Comment by tiagobsbraga** [comment]
@nimaa77 I'm trying add this plugin in my project. I follow the instructions, but I can't run correctly. Not is necessary add AfterScript and AfterStyles?

**Comment by nimaa77** [comment]
@tiagobsbraga hey, forget about that plugin ;)
we merged that library into the after.js core 

read this 
https://github.com/jaredpalmer/after.js/releases/tag/v2.0.0-0

and this
https://github.com/jaredpalmer/after.js/issues/307#issuecomment-610630918

**Comment by tiagobsbraga** [comment]
I followed this steps
[https://github.com/jaredpalmer/after.js/blob/master/UPGRADING.md#migrating-from-v1-to-v2](migrating-from-v1-to-v2)

**And after that, this my output error:** 
`Error: Cannot find module 'undefined'
    at n (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:47925)
    at Module.<anonymous> (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:70058)
    at n (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:124)
    at Module.<anonymous> (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:46223)
    at n (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:124)
    at Object.<anonymous> (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:46138)
    at n (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:124)
    at /Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:1021
    at Object.<anonymous> (/Users/tiagobraga/Documents/work/web/98live-ssr/build/server.js:1:1031)
    at Module._compile (internal/modules/cjs/loader.js:778:30)`

If I remove this line
`const chunks = require(process.env.RAZZLE_CHUNKS_MANIFEST);`

My project run, but I don't see nothing :P

**Comment by BGDSHKA** [comment]
The same error, are there any other options how to solve it?
