### ISSUE TITLE
SSR doesn't support getInitialProps to be synchronous

### ISSUE THREAD

**Issue by necinc** [jaredpalmer/after.js#255]
## Bug, Feature, or Question?
Bug

## Current Behavior
The documentation says that you can implement `getInitialProps` either as synchronous or asynchronous function. The default renderer uses `loadInitialProps` function to collect initial data on the server-side. If we look at the source [code of that function](https://github.com/jaredpalmer/after.js/blob/master/src/loadInitialProps.tsx) it looks like it really supports `async/sync` functions. But after the library build, it transpiles into such code that it clearly expects `getInitialProps` to return a promise.
![image](https://user-images.githubusercontent.com/8607893/68211119-9ee35800-ffdf-11e9-9887-76abf2f17c8c.png)
Which throws next error during the render:
```
TypeError: Cannot read property 'catch' of undefined
        at promises.push (/MY_PROJECT/node_modules/@jaredpalmer/after/src/loadInitialProps.tsx:26:18)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Desired Behavior
To clearly state that `getInitialProps` should be `async` function or refactor the source code to prevent such transpilation quirks

## Suggested Solutions
Don't have anything particular yet. In case some discussion arises can work on it together.

## Additional Information

---

- After.js Version: 1.3.0
- Razzle Version: 3.0.0
- React Version: 16.8.3
- TypeScript Version: -
- OS: macOS 10.15
- Node Version: 10.15.0
- Package Manager and Version: yarn@1.19.1
- Demo Repo or Link:

**Comment by necinc** [comment]
Closing this one too.
