### ISSUE TITLE
Error after upgrading to the latest version

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#328]
## ❓Question
Hello,
I update to the latest version of afterjs & fallowed to upgrading guide, 
but I'm still getting an error, I can't figure out what I did wrong.
can you please look at the error and tell me what I'm missing? 

Cannot find module '@jaredpalmer/after/build/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.@jaredpalmer/after/build/index (/Users/maor/projects/xxxx/external "@jaredpalmer/after/build/index":1:1)
    at __webpack_require__ (/Users/maor/projects/xxxx/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/maor/projects/xxxx/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/common.js (/Users/maor/projects/xxxx/build/server.js:1541:88)
    at __webpack_require__ (/Users/maor/projects/xxxx/build/webpack:/webpack/bootstrap:754:1)
    at fn (/Users/maor/projects/xxxx/build/webpack:/webpack/bootstrap:59:1)

**Comment by nimaa77** [comment]
hello, I think you need to remove node_modules folder and reinstall the modules again

**Comment by stikhomirov** [comment]
@nimaa77 It's not a matter of this question, but in upgrading guide Document.js section example content "TO" and "FROM" are mixed up. It might be confusing, please fix it.
