### ISSUE TITLE
Version 2+ breaks the dynamic option with codesplitting

### ISSUE THREAD

**Issue by Joelgullander** [jaredpalmer/after.js#331]
## ❓Question

Version 1.6 could still handle codesplitting of dynamicly fetched routes. Due to v2+ need of specifying chunkNames this makes async fetching of routes impossible to know ahead of time when building the app. 

Example:

```
const createRoute = (route: FetchedRoute): AsyncRouteProps => {
    return {
        path: route.Url,
        exact: true,
        component: asyncComponent({
            loader: () => import(
            /* webpackChunkName: "[request]" */
            `../common/pages/${route.PageType}`
            ),
            chunkName: route.PageType
        })
    };
  };

const req = fetch('/path/to/sitemap');

const routes = req.data.map(route => createRoute(route));
```

There is no way for webpack to know which pageTypes to chunk if not staticly defining the routes like such:

```
const routes = [
  {
    path: '/',
    exact: true,
    component: Home,
  },
  {
    path: '/about',
    exact: true,
    name: "About",
    }),
  },
  {
    path: '/contact-us',
    exact: true,
    name: "Contact",
  }
];

```

Thoughts on this?

**Comment by nimaa77** [comment]
> There is no way for webpack to know which pageTypes to chunk if not staticly defining the routes:

it's possible with magic comments:
https://webpack.js.org/api/module-methods/#magic-comments
```js
// Multiple possible targets
import(
  /* webpackInclude: /\.json$/ */
  /* webpackExclude: /\.noimport\.json$/ */
  /* webpackChunkName: "[request]" */
  `./locale/${language}`
```

**Comment by Joelgullander** [comment]
Not sure if I follow. In my example it would be 

```
        component: asyncComponent({
            loader: () => import(
            /* webpackInclude: /\.tsx$/ */
            /* webpackChunkName: "[request]" */
            `../common/pages/${route.PageType}`
            ),
```

And this does work during the development build, however when building a production build I still get only one chunk for the first it finds.

In your example above, what if `language` is an unknown string until it has been fetched? How would it know what to name the chunk?

**Comment by Joelgullander** [comment]
Really weird. Can't get it to work. Any chance I could invite you to the repo @nimaa77 to replicate?

**Comment by nimaa77** [comment]
yes just add me to the repo and let's fix this

**Comment by Joelgullander** [comment]
https://github.com/Joelgullander/AfterjsChunks @nimaa77 

The issue is in `src/helpers/mapDynamicRoutesWithComponents.tsx`

Thanks

**Comment by nimaa77** [comment]
I just checked the code and it's really complicated

**Comment by nimaa77** [comment]
but it's possible

**Comment by Joelgullander** [comment]
@nimaa77 I was thinking about codesplitting myself with @loadable-components and thus removing the <AfterScripts /> which works fine, however in SSR it cries over` loadable: SSR requires `@loadable/babel-plugin` even though it is added to the razzle config and babelrc.

Full error message:

```
Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`, please install it
    at invariant (/Users/joelgullander/XX/XX/XX.Client/node_modules/@loadable/component/dist/loadable.cjs.js:17:15)
    at new InnerLoadable (/Users/joelgullander/XX/XX/XX.Client/node_modules/@loadable/component/dist/loadable.cjs.js:117:9)
    at d (/Users/joelgullander/XX/XX/XX.Client/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at $a (/Users/joelgullander/XX/XX/XX.Client/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/Users/joelgullander/XX/XX/XX.Client/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/Users/joelgullander/XX/XX/XX.Client/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at Object.renderToString (/Users/joelgullander/dynamicdog/XX/XX.Client/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at defaultRenderer (/Users/joelgullander/XX/XX/XX.Client/node_modules/@jaredpalmer/after/build/cjs/render.js:130:66)
    at /Users/joelgullander/XX/XX/XX.Client/node_modules/@jaredpalmer/after/build/cjs/render.js:133:61
    at step (/Users/joelgullander/XX/XX/XX.Client/node_modules/@jaredpalmer/after/build/cjs/render.js:44:23) {
```

**Comment by Joelgullander** [comment]
@nimaa77 Can the asyncComponent be used outside of routes? I am thinking about using a * route that fetches data and then render out the desired pagetemplate from that wildcard route. 

Like such:

```
class MasterPage extends Component<IMasterPageProps> {
  public static async getInitialProps({ req, res, match, history, location, ...ctx }: any) {
    // Handle fail to fetch. -:> 404?
    console.log(match, location);
    const request = await axios.get(
      `https://XXXX.XXX.XXX.net/${match.url}?expand=*`, 
      // {
      //   headers: {
      //     'Accept-Language': 'sv'
      //   }
      // }
    );
    return { page: request.data };
  }

  public render() {
    return (
      <div className="MasterPage">
        {mapDynamicPagesWithComponents(this.props.page)}
      </div>
    );
  }
}

export default MasterPage;
```


And here is the lazyloading logic: 

```
import React from 'react';
import { AllPages } from '../types/Episerver/PageTypes';
import { asyncComponent } from '@jaredpalmer/after';

const NewsPage = () => import(/* webpackChunkName: "NewsPage" */ '../common/pages/NewsPage');
const StandardPage = () => import(/* webpackChunkName: "StandardPage" */ '../common/pages/StandardPage');
const StartPage = () => import(/* webpackChunkName: "StartPage" */ '../common/pages/StartPage');

const Pages = {
    NewsPage, 
    StandardPage, 
    StartPage, 
};

export function mapDynamicPagesWithComponents(page: any) {
    // component does exist
    if (typeof Pages[page.customContentType] !== 'undefined') {
        const Comp = asyncComponent({
            loader: Pages[page.customContentType]
        });

        // @ts-ignore
        return <Comp page={page} />;
    }

    // component doesn't exist yet
    return React.createElement(
        () => <div>The page {page.customContentType} has not been created yet.</div>,
        { key: page.contentLink.id }
    );
}
```

This DOES chunk all my pages however it does not get server-rendered, it will get hydrated once the client takes over. Is there any way of making sure it gets rendered aswell?

**Comment by nimaa77** [comment]
I think it's better to specify your route components inside an array first

```js
const HomePage = () => import(/* webpackChunkName="HomePage"  */"./pages/HomePage")
const AboutPage = () => import(/* webpackChunkName="AboutPage"  */"./pages/AboutPage")
const ShopPage = () => import(/* webpackChunkName="ShopPage"  */"./pages/ShopPage")

const pages = [
  HomePage,
  AboutPage,
  ShopPage,
]

const mapRoutesToPages = (routes) => {
  return routes.map((route) => {
    ...route
    component: asyncComponent({
      loader: pages[route.component],
      chunkName: route.component,
    })
  })
}

const routes = await axios.get(/* backend url */);
const appRoutes = mapRoutesToPages(routes);
```

this should do the job

**Comment by nimaa77** [comment]
no, you can't use asyncRoutes outside the routes array

but I think you can use loadable-components for that (it really gets complicated)

> with the new release of react-router (v6) we can implement nested routes easily and in that case each nested component can become a page

**Comment by Joelgullander** [comment]
Thanks for that. Yeah I might need to implement loadable-components, but then again that will require me to skip the AfterScripts section and handle all codesplitting in loadable components. 

Ill try and see what I come up with.
