### ISSUE TITLE
npm start/build crashes

### ISSUE THREAD

**Issue by FMGordillo** [jaredpalmer/after.js#37]
My `package.json` (using `npm init`)

```

{
  "name": "clinical-web-after",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "after start",
    "test": "after test --env=jsdom",
    "build": "after build",
    "start:prod": "NODE_ENV=production node build/build/server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@jaredpalmer/after": "^0.5.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-helmet": "^5.2.0",
    "react-router-dom": "^4.2.2"
  }
}
```

And the error when running `npm start`

```
FMGordillo-MacBookPro:clinical-web-after facundogordillo$ npm start

> clinical-web-after@1.0.0 start /Users/facundogordillo/Documents/Projects/clinical-web-after
> after start

/Users/facundogordillo/Documents/Projects/clinical-web-after/node_modules/@jaredpalmer/after/scripts/start.js:65
async function start() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    ...
```

It also happens with `npm run build`

```

FMGordillo-MacBookPro:clinical-web-after facundogordillo$ npm run build

> clinical-web-after@1.0.0 build /Users/facundogordillo/Documents/Projects/clinical-web-after
> after build

/Users/facundogordillo/Documents/Projects/clinical-web-after/node_modules/@jaredpalmer/after/scripts/build.js:73
async function build(previousFileSizes) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    ...
```

Most probably my mistake, but I want to double check

**Comment by FMGordillo** [comment]
I assume is because of this: https://stackoverflow.com/a/37815872

I will upgrade my Node (currently v6.11.1)

**Comment by FMGordillo** [comment]
Yep, now is working: Node version 8.9.4
