### ISSUE TITLE
`TypeError: reactRouterDom.withRouter is not a function` after using `create-after-app`

### ISSUE THREAD

**Issue by JulianSoto** [jaredpalmer/after.js#510]
### Current Behavior

Console throws an error while compiling the client (server compiles successfully) after running `yarn start`:

`TypeError: reactRouterDom.withRouter is not a function`

![image](https://user-images.githubusercontent.com/21326208/141040735-2a6b014d-8f8e-4c27-a967-7d5626ec13e5.jpg)

I bootstrapped the project using `create-after-app`. I didn't modify anything when I ran into this issue.

### Expected behavior

Client and Server should compile with no issues:

![image2](https://user-images.githubusercontent.com/21326208/141041465-33aa7205-9a85-4d28-a268-052f975a36a3.jpg)

### Reproducible example

Run either `npx create-after-app` or `yarn create after-app` to init a new after.js app, and then `yarn start`.

### Suggested solution(s)

Apparently After doesn't work with `react-router-dom` version 6. I downgraded react-router-dom to v5.3.0 and seems to work well. I believe `withRouter` is deprecated. `create-after-app` should install an older `react-router-dom` version other than v6.x.x or update `after.js` to use v6 with react hooks instead. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | ^17.0.2
| After.js         | ^0.8.2
| Razzle           | ^4.2.6
| TypeScript       | N/A
| Node             | 16.7.0
| npm/Yarn         | yarn v1.22.11
| Operating System | Ubuntu 20

**Comment by mstroiu** [comment]
I have the same issue after upgrading `react-router-dom` to `6.0.2`.

Below are the errors that I get:

```bash
ERROR in ./node_modules/@jaredpalmer/after/dist/esm/After.esm.js 139:25-31
export 'Switch' (imported as 'Switch') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, renderMatches, resolvePath, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useParams, useResolvedPath, useRoutes, useSearchParams)
 @ ./node_modules/@jaredpalmer/after/dist/esm/index.esm.js 2:0-39 2:0-39
 
 ERROR in ./node_modules/@jaredpalmer/after/dist/esm/After.esm.js 144:81-89
export 'Redirect' (imported as 'Redirect') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, renderMatches, resolvePath, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useParams, useResolvedPath, useRoutes, useSearchParams)
 @ ./node_modules/@jaredpalmer/after/dist/esm/index.esm.js 2:0-39 2:0-39
 
 ERROR in ./node_modules/@jaredpalmer/after/dist/esm/After.esm.js 170:25-35
export 'withRouter' (imported as 'withRouter') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, renderMatches, resolvePath, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useParams, useResolvedPath, useRoutes, useSearchParams)
 @ ./node_modules/@jaredpalmer/after/dist/esm/index.esm.js 2:0-39 2:0-39
 
 ERROR in ./node_modules/@jaredpalmer/after/dist/esm/renderApp.esm.js 133:67-79
export 'StaticRouter' (imported as 'StaticRouter') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, renderMatches, resolvePath, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useParams, useResolvedPath, useRoutes, useSearchParams)
 @ ./node_modules/@jaredpalmer/after/dist/esm/index.esm.js 8:0-47 8:0-47
```

```bash
node_modules/@jaredpalmer/after/src/After.tsx:199
export const After = withRouter(Afterparty);
                     ^
TypeError: reactRouterDom.withRouter is not a function
    at Object.<anonymous> (node_modules/@jaredpalmer/after/src/After.tsx:199:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (node_modules/@jaredpalmer/after/dist/index.js:7:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

The solution is to downgrade to `react-router-dom 5.3.0`

**Comment by tehraven** [comment]
Bump this right out of stale.

After.js is not currently compatible with React-Router V6. I'm sure Jared would appreciate a clean PR with the changes, if anyone's got the time ❤️
