### ISSUE TITLE
fs.copyfile is not a function

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/after.js#65]
```
node_modules/@jaredpalmer/after/scripts/start.js:100
      fs.copyFile(changedPath, tempSrc.replace('src', changedPath), err => {
         ^

TypeError: fs.copyFile is not a function
    at FSWatcher.chokidar.watch.on.changedPath (/home/paul/web/-cart/node_modules/@jaredpalmer/after/scripts/start.js:100:10)
    at emitTwo (events.js:125:13)
    at FSWatcher.emit (events.js:213:7)
    at FSWatcher.<anonymous> (/home/paul/web/-cart/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/home/paul/web/-cart/node_modules/chokidar/index.js:240:5)
    at FSWatcher.<anonymous> (/home/paul/web/-cart/node_modules/chokidar/lib/nodefs-handler.js:263:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elastic-cart@1.0.0 start: `after start`

```

I get this error after following the guide and saving a change in either Home or About.

also tried erasing everything and starting from scratch.

node v8.4.0
npm v5.6

**Comment by paOol** [comment]
upgrading to node v8.9 LTS seems to have fixed this.
