### ISSUE TITLE
Sass webpack extension breaks typescript example

### ISSUE THREAD

**Issue by eschmar** [jaredpalmer/after.js#75]
Beginner here and I'm trying to integrate sass-loader into the `with-typescript` example. Unfortunately, it seems to break the project. Appending the following:

```js
// after.config.js

...
// Locate css loader and remove it
config.module.rules.filter(rule => !(rule.test && String(rule.test) === String(/\.css$/)));

// Declare scss loader configuration
config.module.rules.push({
    test: /\.(sass|scss)$/,
    use: ['style-loader', 'css-loader', 'sass-loader']
});
...
```

results in:

```sh
 DONE  Compiled successfully

Your application is running at http://localhost:3000

<project-path>/with-typescript/build/build/server.js:1473
	return window && document && document.all && !window.atob;
	^

ReferenceError: window is not defined
    at <project-path>/with-typescript/build/build/server.js:1473:2
    at <project-path>/with-typescript/build/build/server.js:1462:46
    at __dirname../node_modules/style-loader/lib/addStyles.js.module.exports (<project-path>/with-typescript/build/build/server.js:1507:46)
    at Object../build/src/scss/bootstrap.scss (<project-path>/with-typescript/build/build/server.js:1189:81)
    at __webpack_require__ (<project-path>/with-typescript/build/build/server.js:630:30)
    at fn (<project-path>/with-typescript/build/build/server.js:48:20)
    at Object../build/src/Home.tsx (<project-path>/with-typescript/build/build/server.js:744:79)
    at __webpack_require__ (<project-path>/with-typescript/build/build/server.js:630:30)
    at fn (<project-path>/with-typescript/build/build/server.js:48:20)
    at Object../build/src/_routes.tsx (<project-path>/with-typescript/build/build/server.js:1080:64)
```

Unfortunately, I couldn't find any examples for after.js directly and the ones for razzle didn't help - they have the approach of only including the sass loader on `target === "web"` and ignoring for the `node` target. Then the setup compiles properly, however the dev and production build appear to load the scss multiple times. My scss file only contains `body { background-color: purple; }`. On page load, the background is purple, changes back to white, then back to purple again. Best described as flickering.

I feel like I'm missing something fundamental here and would appreciate if someone could shed some light into this. Thanks in advance!

**Comment by eschmar** [comment]
I have found a solution working:

```js
// after.config.js
const ExtractTextPlugin = require('extract-text-webpack-plugin')


...
// Locate css loader and remove it
config.module.rules.filter(rule => !(rule.test && String(rule.test) === String(/\.css$/)));

// Declare scss loader configuration
config.module.rules.push({
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: 'css-loader!sass-loader'
  })
});

config.plugins.push(
  new ExtractTextPlugin('static/css/[name].[contenthash:8].css')
)
...
```

ExtractTextPlugin to the rescue. This can be closed, although some explanations towards the use case for target distinction would be appreciated.
